"""empty message

Revision ID: 28da2c3a81e9
Revises: 
Create Date: 2020-06-16 00:57:36.738162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28da2c3a81e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('passowrd', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('passowrd', sa.String(length=256), nullable=True),
    sa.Column('teacher', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('teacher')
    # ### end Alembic commands ###
