"""empty message

Revision ID: 8bbb17751fcd
Revises: 93408521f0ee
Create Date: 2020-06-16 12:44:38.799325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbb17751fcd'
down_revision = '93408521f0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('joinCode', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_class',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], )
    )
    op.create_index(op.f('ix_student_slug'), 'student', ['slug'], unique=False)
    op.create_index(op.f('ix_teacher_slug'), 'teacher', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_slug'), table_name='teacher')
    op.drop_index(op.f('ix_student_slug'), table_name='student')
    op.drop_table('student_class')
    op.drop_table('class')
    # ### end Alembic commands ###
