"""empty message

Revision ID: 93408521f0ee
Revises: afb774961433
Create Date: 2020-06-16 01:25:31.389136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93408521f0ee'
down_revision = 'afb774961433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.drop_constraint('student_teacher_fkey', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'teacher', ['teacher_id'], ['id'])
    op.drop_column('student', 'teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('teacher', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_teacher_fkey', 'student', 'teacher', ['teacher'], ['id'])
    op.drop_column('student', 'teacher_id')
    # ### end Alembic commands ###
