"""empty message

Revision ID: f3e2e2fd9b5d
Revises: 5c5c4a70129b
Create Date: 2020-06-17 01:37:49.917928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e2e2fd9b5d'
down_revision = '5c5c4a70129b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teacher_slug', table_name='teacher')
    op.create_index(op.f('ix_teacher_slug'), 'teacher', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_slug'), table_name='teacher')
    op.create_index('ix_teacher_slug', 'teacher', ['slug'], unique=False)
    # ### end Alembic commands ###
